export const ROUTE_PATHS = {
  root: '/',
  login: '/login',
  signup: '/signup',
  signupAgreement: '/signup-agreement',
  signupComplete: '/signup-complete',
  onboarding: '/onboarding',
  home: '/home',
  activities: '/activities',
  activityEnvironment: '/activities/environment',
  activitySocial: '/activities/social',
  activityGovernance: '/activities/governance',
  finance: '/finance',
  my: '/my',
  chatbot: '/chatbot',
} as const
